steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - kms
  - decrypt
  - --ciphertext-file=env.production.yaml.enc
  - --plaintext-file=./env.yaml
  - --location=global
  - --keyring=${_KEYRING}
  - --key=${_KEY}
  - --verbosity=debug
- name: 'gcr.io/cloud-builders/gcloud'
  id: "New Arrival"
  args:
  - functions
  - deploy
  - 'ArrivalCreateSub'
  - --trigger-event=providers/cloud.firestore/eventTypes/document.create
  - --trigger-resource=projects/epi-belize/databases/(default)/documents/arrivals/{pushId}
  - --runtime=go113
  - --entry-point=ArrivalsListener
  - --region=us-east1
  - --env-vars-file=env.yaml
  dir: .
- name: 'gcr.io/cloud-builders/gcloud'
  id: "Update Arrival"
  args:
  - functions
  - deploy
  - 'ArrivalUpdateSub'
  - --trigger-event=providers/cloud.firestore/eventTypes/document.update
  - --trigger-resource=projects/epi-belize/databases/(default)/documents/arrivals/{pushId}
  - --runtime=go113
  - --entry-point=ArrivalsListener
  - --region=us-east1
  - --env-vars-file=env.yaml
  dir: .
substitutions:
  _KEYRING: functions-deployment
  _KEY: entry-screening-func
